spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/resources
    livereload:
      enabled: true
  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: com.yodean.oa
  config-locations: classpath*:mybatis-config.xml
  mapper-locations: mapper/*.xml