server:
  port: 8080
  servlet:
    context-path: /oa



configuration:
  document: /Users/rick/jkxyx205/tmp/oa #文件上传根路径
  cdn: http://cdn-oa.yodean.com

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oa?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: sgcc
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate.format_sql: true