spring:
  profiles:
    active: dev

mybatis:
  type-aliases-package: com.yodean.oa
  config-locations: classpath*:mybatis-config.xml
  mapper-locations: mapper/*.xml

#mybatis_config_file: mybatis-config.xml
#mapper_path: mapper/*.xml
#mybatis