server:
  port: 8080
  servlet:
    context-path: /oa



configuration:
  document: /root/oa #文件上传根路径
  cdn: http://207.148.100.137:80         #nginx静态服务器
  tmp: /root/oa/tmp     #临时目录
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://207.148.100.137:3306/oa?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: jkxyx205
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate.format_sql: true